# Numpy

## Introduction

NumPy is an open-source library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

### How to install Numpy

In [1]:
# pip install numpy

### How to import Numpy

In [2]:
import numpy as np

In [9]:
a = np.arange(10)
print(a)
a.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

In [12]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5 6 7 8 9]]


(1, 10)

## What is array?
An array in programming refers to a data structure that contains a collection of items.

In [14]:
a = np.array([1, 2, 3, 4, 5, 6, 7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [17]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(b)
b.shape


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


(4, 4)

In [19]:
c = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]])
print(c)
c.shape


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]


(1, 4, 4)

In [23]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.empty([2,2])

array([[0., 0.],
       [0., 0.]])

In [34]:
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [41]:
x = np.ones(2, dtype=np.int32)
print(x)

[1 1]


In [43]:
type(x)

numpy.ndarray

In [42]:
x.dtype

dtype('int32')

In [45]:
x = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(x)

[2 1 5 3 7 4 6 8]


In [46]:
np.sort(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
y = np.array([5,6,7,8,9,10, 11, 12])

In [52]:
e = np.array([5,6,7,8,9,10, 11])

In [50]:
z = x + y
print(z)

[ 7  7 12 11 16 14 17 20]


In [55]:
np.concatenate((x,y))

array([ 2,  1,  5,  3,  7,  4,  6,  8,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [59]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(a)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [64]:
a.ndim

3

In [65]:
a.size

24

In [66]:
a.shape

(3, 2, 4)

In [68]:
b = a.reshape(3, 8)
print(b)

[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]


In [73]:
b.ndim

2

In [70]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [72]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [77]:
c = a.reshape(1, 2,3)
print(c)

[[[0 1 2]
  [3 4 5]]]


In [83]:
d = np.arange(24)
print(c)

[[[0 1 2]
  [3 4 5]]]


In [100]:
c = d.reshape(6,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [98]:
c.ndim

3

In [102]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [104]:
a1 = a[np.newaxis, :]
print(a1)
a1.shape

[[1 2 3 4 5 6]]


(1, 6)

In [106]:
a2 = a[:, np.newaxis]
print(a2)
a2.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [109]:
b = np.expand_dims(a, axis=0)
print(b)
b.shape

[[1 2 3 4 5 6]]


(1, 6)

In [110]:
a = np.array([1, 2, 3, 4, 5, 6])

In [111]:
a[1]

2

In [114]:
a[1:4]

array([2, 3, 4])

In [118]:
a[:-2]

array([1, 2, 3, 4])

In [119]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [122]:
print(a[a > 6])

[ 7  8  9 10 11 12]


In [126]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [124]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [127]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [128]:
np.hsplit(a1, 2)

[array([[1],
        [2]]),
 array([[1],
        [2]])]

In [129]:
np.vsplit(a1, 2)

[array([[1, 1]]), array([[2, 2]])]

In [130]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [131]:
b1 = a[0, :]
print(b1)

[1 2 3 4]


In [133]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [134]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [137]:
a.sum()

176

In [138]:
a.min()

2

In [139]:
a.max()

99

In [141]:
a.argmax()

0

In [142]:
a.argmin()

1

In [151]:
a * 4

array([[396,   8,  12,  16],
       [ 20,  24,  28,  32],
       [ 36,  40,  44,  48]])

In [152]:
a*([1,2,3,4])

array([[99,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48]])

In [153]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [156]:
data[1:2]

array([[3, 4]])

In [157]:
data[0:2, 0]

array([1, 3])

In [158]:
data.max(axis=0)

array([5, 6])

In [159]:
data.min(axis=0)

array([1, 2])

In [160]:
data.max(axis=1)

array([2, 4, 6])

In [161]:
data.min(axis=0)

array([1, 2])

In [172]:
a = np.random.default_rng()
a.random(8)

array([0.77860677, 0.14640184, 0.33772819, 0.9474762 , 0.79885972,
       0.53532128, 0.94095065, 0.80013964])

In [185]:
b = np.random.randint(1, 20, size=10)
print(b)

[ 4 14 15 17 15  3  4 18 16 16]
